name: Update Issue

on:
  workflow_dispatch:

jobs:
  update_issue:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v3
        
    - name: Update Issue
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: 2
        body: |
          Hello, this is an updated discussion.
          With multiple lines.
        reactions: hooray
