name: Edit Issue

on:
  workflow_dispatch:

jobs:
  edit_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Edit issue
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { issues } = github;
            const issue_number = core.getInput('issue_number');
          
            const issue = await issues.get({owner: context.repo.owner, repo: context.repo.repo, issue_number: 2});
            issue.title = "New issue title";
            issue.body = "New issue body";
            issues.update(issue);
