name: Update Issue

on:
  workflow_dispatch:

jobs:
  update_issue:
    runs-on: ubuntu-latest

    steps:
    
    - name: Update Issue
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        repository: e-gugliotti-NOAA/github-actions-test
        issue-number: 2
        body: |
          Hello, this is an updated discussion.
          With multiple lines.
        reactions: hooray
