name: Update Issue

on:
  workflow_dispatch:

jobs:
  update_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Edit issue
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue = await issues.get({owner: context.repo.owner, repo: context.repo.repo, issue_number: 2});
          issue.title = "New issue title";
          issue.body = "New issue body";
          issues.update(issue);
