name: add ss3 to path
on: 
  workflow_dispatch:

jobs:
  add-ss3-to-path:
    runs-on: ubuntu-latest

    steps:
      
      - name: install libcurl
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
        
      - name: Get the latest SS3 executable and put in path
        run:  |
          wget -O ss3 https://github.com/nmfs-stock-synthesis/stock-synthesis/releases/latest/download/ss_linux
          sudo chmod a+x ss3
          mv ss3 /usr/local/bin/ss3
          echo "/usr/local/bin/ss3" >> $GITHUB_PATH
          echo $PATH
