name: add ss3 to path
on: 
  workflow_dispatch:

jobs:
  add-ss3-to-path:
    runs-on: ubuntu-latest

    steps:
      
      - name: checkout rep
        uses: actions/checkout@v3
      
      - name: install libcurl
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: setup R  
        uses: r-lib/actions/setup-r@v2
        
      - name: Get the latest SS3 executable and put in path
        run:  |
          wget -O ss3 https://github.com/nmfs-stock-synthesis/stock-synthesis/releases/latest/download/ss_linux
          sudo chmod a+x ss3
          mv ss3 /usr/local/bin/ss3
          echo $PATH
          export PATH=/usr/local/bin/ss3:$PATH
          echo "/usr/local/bin/ss3" >> $GITHUB_PATH
          echo $PATH
          
      - name: see if R can detect ss3
        run: |
          Sys.which("ss3")
        shell: Rscript {0}
        
      - name: Setup git user
        uses: fregante/setup-git-user@v1
        
      - name: Create Pull Request 
        uses: peter-evans/create-pull-request@v3
        with:
          commit_message: Update model files to new ss exe
          branch: add-update-workflow-new
          title: 'Update model files to new ss exe'
      
      - name: Get the ss last tag on unix
        id: get-latest-tag-unix
        run: |
          latest_tag=$(git ls-remote --tags https://github.com/nmfs-stock-synthesis/stock-synthesis.git | tail -1 | sed 's/.*\/v//')
          echo "tag=${latest_tag}" >> $GITHUB_OUTPUT
          
      - name: Get the ss last tag on unix
        id: get-latest-tag-repo-unix
        run: |
          latest_tag_repo=$(git ls-remote --tags | tail -1 | sed 's/.*\/v//')
          echo "tag=${latest_tag_repo}" >> $GITHUB_OUTPUT
          
      - name: create tag
        uses: mathieudutour/github-tag-action@v6.1
        if: ${{ steps.get-latest-tag-unix.outputs.tag != steps.get-latest-tag-repo-unix.outputs.tag}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get-latest-tag-unix.outputs.tag }}
       
